# API Health check endpoint
GET http://localhost:3333/health

###

# API POST Endpoint to create a user
POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doeee@example.com",
    "password": "password"
}

###

# API POST Endpoint to login a user
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password"
}

###

# API GET Endpoint to fetch user buying requests
GET http://localhost:3333/requests
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjExYTUzYi1kNjIxLTRhMTktYjgyZi04YjI1Y2IzNjZhYmQiLCJyb2xlIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTc3ODc0NjYsImV4cCI6MTc1Nzc5MTA2Nn0.RmqIJRCxalGPXrjgE3bF95rz9MbglBJbADqfoi3msXo

###

# API POST Endpoint to create a buying request
POST http://localhost:3333/requests
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjExYTUzYi1kNjIxLTRhMTktYjgyZi04YjI1Y2IzNjZhYmQiLCJyb2xlIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTc3ODc0NjYsImV4cCI6MTc1Nzc5MTA2Nn0.RmqIJRCxalGPXrjgE3bF95rz9MbglBJbADqfoi3msXo
Content-Type: application/json

{
    "title": "New Purchase Request",
    "description": "Requesting new office supplies",
    "quantity": 10,
    "totalPrice": 150,
    "items": [
        {
            "title": "Item 1",
            "description": "Description for Item 1",
            "quantity": 5,
            "price": 30
        },
        {
            "title": "Item 2",
            "description": "Description for Item 2",
            "quantity": 5,
            "price": 30
        }
    ]
}

###

# API GET Endpoint to fetch a specific buying request by ID
GET http://localhost:3333/requests/02cb950b-81a8-43dc-9c29-64ed524901b2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjExYTUzYi1kNjIxLTRhMTktYjgyZi04YjI1Y2IzNjZhYmQiLCJyb2xlIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTc3ODc0NjYsImV4cCI6MTc1Nzc5MTA2Nn0.RmqIJRCxalGPXrjgE3bF95rz9MbglBJbADqfoi3msXo

