version: '3.9'
services:
  db:
    image: mysql:8.4
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./databse/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-db-network

volumes:
  db_data:

networks:
  mysql-db-network:
    driver: bridge
